name: Release to crates.io and GitHub

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --all
      - run: cargo build --release
      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: gitshift
          path: target/release/gitshift

  publish-cratesio:
    name: Publish to crates.io
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Extract version from Git tag
        id: extract_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Update Cargo.toml version
        run: |
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --allow-dirty

  build-all:
    name: Build for All Platforms
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-amd64
            artifact_name: gitshift
            asset_name: gitshift-linux-amd64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: darwin-amd64
            artifact_name: gitshift
            asset_name: gitshift-macos-amd64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: darwin-arm64
            artifact_name: gitshift
            asset_name: gitshift-macos-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows-amd64
            artifact_name: gitshift.exe
            asset_name: gitshift-windows-amd64.exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

